version: "3"
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
      - redis
  redis:
    container_name: redis
    image: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6379:6379"
  spring:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - redis